### ISSUE TITLE
the blog need to support api for apps

### ISSUE THREAD

**Issue by Ivin0022** [tangsect-arch/python-blog#1]
[Foreign key reference](https://docs.djangoproject.com/en/3.0/topics/db/examples/many_to_one/)

in the example in the above link it will show how to access a the postimages from entries, 

[APIView reference](https://www.django-rest-framework.org/api-guide/views/#class-based-views)

``` python
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.contrib.auth.models import User

class ListUsers(APIView):
    """
    View to list all users in the system.

    - Requires token authentication.
    - Only admin users are able to access this view.

    """
    authentication_classes = [authentication.TokenAuthentication]
    permission_classes = [permissions.IsAdminUser]

    def get(self, request, format=None):
        """
        Return a list of all users.
        """
        usernames = [user.username for user in User.objects.all()]
        return Response(usernames)
```

[Serializer reference](https://www.django-rest-framework.org/api-guide/serializers/#dealing-with-nested-objects)

### Nested serializer

``` python
class UserSerializer(serializers.Serializer):
    email = serializers.EmailField()
    username = serializers.CharField(max_length=100)

class CommentSerializer(serializers.Serializer):
    user = UserSerializer()
    content = serializers.CharField(max_length=200)
    created = serializers.DateTimeField()
```

### Nested list serializer

use a serializer with `many=True` if you are dealing with a foreign key 

``` python
class CommentSerializer(serializers.Serializer):
    user = UserSerializer(required=False)
    edits = EditItemSerializer(many=True)  # A nested list of 'edit' items.
    content = serializers.CharField(max_length=200)
    created = serializers.DateTimeField()
```

# your task

make a api for this blog app, so that it can be integrated with a mobile app

**Comment by tangsect-arch** [comment]
searilizer
from rest_framework import  serializers
from entries.models import Entries, Likes, PostImages



class entriesSerializers(serializers.ModelSerializer):
    def get_username_from_entry_author(self,entries):
        username = entries.entry_author.username


    username = serializers.SerializerMethodField(get_username_from_entry_author)
    print(username, ' username')
    
    class Meta:
        model = Entries
        fields = ('entry_title','entry_text','liked','entry_date','entry_author','entry_images','username')
        #fields = '__all__'

    


class likesSerializers(serializers.ModelSerializer):
    class Meta:
        model = Likes
        #fields = ('user','entries','value')
        fields = '__all__'

class postImagesSerializers(serializers.ModelSerializer):
    class Meta:
        model = PostImages
        fields = ['entries','images']
        #fields = '__all__'




view
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import  status
from entries.models import Entries, Likes, PostImages
from .serializers import  likesSerializers, postImagesSerializers, entriesSerializers
from rest_framework.pagination import LimitOffsetPagination,PageNumberPagination


class entryList(APIView):
    def get(self, request):
        model = Entries.objects.all()
        print(model,' model')
        serializer = entriesSerializers(model,many=True)
        #pagination_class = LimitOffsetPaginationcd#PageNumberPagination
        return Response(serializer.data)


# class entryPost(viewsets.ModelViewSet):
#     print('bbbbbbbbbbbbbbbbbbbb')
#     qs =  Entries.objects.all()
#     serializer_class = entriesSerializers(qs)


class photoList(APIView):
    def get(self, request):
        images = PostImages.objects.all()
        print(images,' tttttttttttt')
        serializers = postImagesSerializers(images,many=True)
        return Response(serializers.data)

**Comment by tangsect-arch** [comment]
the above one includes my searilizer file and view file. 
entryList(APIView) is not returning the fields of PostImages model. Can you help and point out what should i do.

**Comment by Ivin0022** [comment]
serializer_class = entireserializer
that's it,  no need to call it with a queryset

**Comment by Ivin0022** [comment]
can you please commit it and show me next time... rather than posting it here

**Comment by tangsect-arch** [comment]
Ok

**Comment by tangsect-arch** [comment]
Have some problem working with nested searilizer. Worked around it with directly calling different searilizers and then push the value(userapi/view/entry_list_view_item_detail)

**Comment by tangsect-arch** [comment]
Haven't completed posting multiple images and authentication tokens

**Comment by tangsect-arch** [comment]
Completed

**Comment by tangsect-arch** [comment]
I couldn't implement nested serailizer for the multiple image. Instead include a loop n then save the images after saving the data to Entries table.
